apiVersion: v1
kind: ConfigMap
metadata:
    name: config-service7
    labels:
        name: config-service7
    namespace: hydragen
data:
    conf.json: '{"processes":10,"logging":true,"protocol":"grpc","endpoints":[{"name":"endpoint1","execution_mode":"sequential","cpu_complexity":{"execution_time":0.001,"threads":1},"network_complexity":{"forward_requests":"synchronous","response_payload_size":256,"called_services":[{"service":"service8","port":80,"endpoint":"endpoint1","protocol":"grpc","traffic_forward_ratio":1,"request_payload_size":512}]}}]}'
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: service7
    namespace: hydragen
    labels: {}
spec:
    selector:
        matchLabels:
            app: service7
            version: ""
    replicas: 1
    template:
        metadata:
            labels:
                app: service7
                version: ""
            annotations:
                sidecar.istio.io/proxyCPU: 2000m
                sidecar.istio.io/proxyCPULimit: 2000m
                sidecar.istio.io/statsInclusionPrefixes: cluster.outbound,cluster_manager,listener_manager,http_mixer_filter,tcp_mixer_filter,server,cluster.xds-grp,listener,connection_manager
                sidecar.istio.io/statsInclusionRegexps: http.*
                sidecar.istio.io/userVolume: '[{"name":"rate-limit-filter","configMap":{"name":"rate-limit-filter"}}]'
                sidecar.istio.io/userVolumeMount: '[{"mountPath":"/var/local/wasm","name":"rate-limit-filter"}]'
        spec:
            nodeName: worker2
            containers:
                - name: app
                  image: yizhengx/hydragen:chain-d8-grpc
                  imagePullPolicy: IfNotPresent
                  env:
                    - name: SERVICE_NAME
                      value: service7
                    - name: GOMEMLIMIT
                      value: "1024000000"
                  ports:
                    - containerPort: 5000
                  volumeMounts:
                    - mountPath: /usr/src/emulator/config
                      name: config-data-volume
                  readinessProbe:
                    exec:
                        command: [/usr/bin/grpc_health_probe, '-addr=:5000']
                    initialDelaySeconds: 2
                    periodSeconds: 1
                  resources:
                    limits:
                        cpu: 1000m
                        memory: 1024M
                    requests:
                        cpu: 1000m
                        memory: 512M
            volumes:
                - name: config-data-volume
                  configMap:
                    name: config-service7
---
apiVersion: v1
kind: Service
metadata:
    name: service7
    namespace: hydragen
    labels: {}
    annotations:
        grpc: /
spec:
    selector:
        app: service7
    ports:
        - name: grpc
          port: 80
          targetPort: 5000
